from tl_classifier import TLClassifier
from opencv_tl_classifier import OpenCVTLClassifier
from ssd_tl_classifier import SSDTLClassifier
from light_classification.yolo.yolo_tiny_tl_classifier import YOLOTinyTLClassifier
